image: Visual Studio 2022
configuration: Release
platform: x64

build: off

build_script:
  - ps: |
      # Force MSBuild to use the 19041 version which we know is on the disk
      $sdkVer = "10.0.19041.0"
      msbuild UsbAsRam.vcxproj `
        /p:Configuration=Release `
        /p:Platform=x64 `
        /p:WindowsTargetPlatformVersion=$sdkVer `
        /p:TargetPlatformVersion=$sdkVer `
        /p:LatestTargetPlatformVersion=$sdkVer `
        /p:SpectreMitigation=false `
        /v:m `
        /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: 'x64\Release\*.sys'
    name: Driver
