/*++
Module Name: DriverEntry.cpp
Abstract: KMDF driver entry and tracing. Modules 2–5 are implemented in DmaIo.cpp,
         Compression.cpp, and WbCache.cpp (see objective.md).
Environment: Kernel mode, Windows 11, KMDF
--*/

#include <ntddk.h>
#include <wdf.h>

extern "C" {

EVT_WDF_DRIVER_DEVICE_ADD UsbAsRamEvtDeviceAdd;

DRIVER_INITIALIZE DriverEntry;

static VOID
UsbAsRamEvtDriverUnload(
    _In_ WDFDRIVER Driver
    );

}

//
// Tracing: DbgPrintEx is always available. WPP is prepared via macros that mirror
// the usual WPP_* pattern so a later RUN_WPP pass can swap in tracewpp output.
//
#define USR_LOG_COMPONENT "UsbAsRam"

#define UsbAsRamTraceError(_fmt, ...) \
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, \
        "[" USR_LOG_COMPONENT ":ERR] " _fmt "\n", __VA_ARGS__)

#define UsbAsRamTraceInfo(_fmt, ...) \
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, \
        "[" USR_LOG_COMPONENT ":INF] " _fmt "\n", __VA_ARGS__)

#define UsbAsRamTraceVerbose(_fmt, ...) \
    DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_TRACE_LEVEL, \
        "[" USR_LOG_COMPONENT ":VRB] " _fmt "\n", __VA_ARGS__)

//
// Placeholder for WPP: when you add a .mc file and RUN_WPP to the project,
// replace the DbgPrintEx macros above with #include "UsbAsRam.tmh" generated by tracewpp,
// and call WPP_INIT_TRACING / WPP_CLEANUP below.
//
#ifndef WPP_INIT_TRACING
#define WPP_INIT_TRACING(DriverObject, RegistryPath) ((VOID)0)
#define WPP_CLEANUP(DriverObject) ((VOID)0)
#endif

static VOID
UsbAsRamEvtDriverUnload(
    _In_ WDFDRIVER Driver
    )
{
    UNREFERENCED_PARAMETER(Driver);

    UsbAsRamTraceInfo("%s: driver unload", __FUNCTION__);
    WPP_CLEANUP(WdfDriverWdmGetDriverObject(Driver));
}

NTSTATUS
DriverEntry(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PUNICODE_STRING RegistryPath
    )
{
    WDF_DRIVER_CONFIG config;
    WDF_OBJECT_ATTRIBUTES attributes;
    NTSTATUS status;

    WPP_INIT_TRACING(DriverObject, RegistryPath);

    UsbAsRamTraceInfo("%s: USB-as-RAM filter driver loading, RegistryPath=%wZ",
        __FUNCTION__, RegistryPath);

    WDF_DRIVER_CONFIG_INIT(&config, UsbAsRamEvtDeviceAdd);
    config.EvtDriverUnload = UsbAsRamEvtDriverUnload;

    WDF_OBJECT_ATTRIBUTES_INIT(&attributes);
    attributes.EvtCleanupCallback = NULL;

    status = WdfDriverCreate(
        DriverObject,
        RegistryPath,
        WDF_NO_OBJECT_ATTRIBUTES,
        &config,
        WDF_NO_HANDLE);

    if (!NT_SUCCESS(status)) {
        UsbAsRamTraceError("%s: WdfDriverCreate failed: 0x%08X", __FUNCTION__, status);
        WPP_CLEANUP(DriverObject);
        return status;
    }

    UsbAsRamTraceInfo("%s: WdfDriverCreate succeeded", __FUNCTION__);
    return status;
}
