image: Visual Studio 2022
configuration: Release
platform: x64

build:
  project: UsbAsRam.vcxproj
  verbosity: minimal
  # This line forces MSBuild to use the right settings
  options: /p:Configuration=Release /p:Platform=x64

artifacts:
  - path: 'x64\Release\*.sys'
    name: Driver
  - path: 'x64\Release\*.inf'
    name: DriverInfo
